// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewFileNode struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	IsFolder    bool    `json:"isFolder"`
	MimeType    *string `json:"mimeType"`
	File        *string `json:"file"`
}

type FileNode struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	IsFolder    bool       `json:"isFolder"`
	MimeType    *string    `json:"mimeType"`
	File        *string    `json:"file"`
	Children    []FileNode `json:"children"`
}
