// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type CreateFileNode struct {
	Name        string  `json:"name"`
	Path        string  `json:"path"`
	Description string  `json:"description"`
	IsFolder    bool    `json:"isFolder"`
	MimeType    *string `json:"mimeType"`
}

type FileNode struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	IsFolder    bool       `json:"isFolder"`
	MimeType    *string    `json:"mimeType"`
	Size        int64      `json:"size"`
	Children    []FileNode `json:"children"`
}
