// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateFileNode struct {
	Name        string          `json:"name"`
	Path        string          `json:"path"`
	Description string          `json:"description"`
	IsFolder    bool            `json:"isFolder"`
	MimeType    *string         `json:"mimeType"`
	File        *graphql.Upload `json:"file"`
}

type FileNode struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	IsFolder    bool       `json:"isFolder"`
	MimeType    *string    `json:"mimeType"`
	Children    []FileNode `json:"children"`
	Size        int64      `json:"size"`
}
